config/routes.rb
Rails.application.routes.draw do
  resources :reviews
  resources :bookings
  resources :searches
  resources :bookmarks
  resources :tours
  resources :customers
  resources :agents
  resources :admins

  root 'static_page#home'

  get 'bookmarks/potential_buyers/:tour_id', to: 'bookmarks#potential_buyers'
  get 'bookmarks/add/:customer_id/:tour_id', to: 'bookmarks#add'
  get '/bookings/new/:tour_id', to: 'bookings#new'
  get '/bookings/:booking_id/:tour_id', to: 'bookings#destroy'
  get '/reviews/:customer_id/:tour_id', to: 'reviews#new'

  # get '/partial_delete/:booking_id', to: 'bookings#partial_delete'
  # get '/partial_delete/bookings/:booking_id/:seats_booked', to: 'bookings#partial_delete'

  get '/home', to: 'static_page#home'
  get    '/signup',  to: 'sessions#redirect'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'




  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord

  EMAIL_FORMAT = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :email, presence: true, uniqueness: { case_sensitive: false, message: "This account already exists. Go to Login" }, format: { with: EMAIL_FORMAT }
  validates :password, presence: true, confirmation: true


  has_secure_password
  validates :password, presence: true, length: { minimum: 8 }

end

app/models/agent.rb
class Agent < ApplicationRecord
  has_many :tours, dependent: :destroy


  EMAIL_FORMAT = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: { case_sensitive: false,   message: "This account already exists. Go to Login" }, format: { with: EMAIL_FORMAT }
  validates :name, presence: true
  validates :password, presence: true, confirmation: true

  has_secure_password
  validates :password, presence: true, length: { minimum: 8 }

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :customer
  belongs_to :tour

  validates :seats_booked, :numericality => { greater_than: 0}
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :customer
  belongs_to :tour

  validates :customer_id, presence: true
  validates :tour_id, presence: true
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :bookings, dependent: :destroy

  EMAIL_FORMAT = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: { case_sensitive: false,   message: "This account already exists. Go to Login"  }, format: { with: EMAIL_FORMAT }
  validates :name, presence: true
  validates :password, presence: true, confirmation: true

  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

end

app/models/review.rb
class Review < ApplicationRecord
end

app/models/search.rb
class Search < ApplicationRecord
  def search_tours
    num_1 = 1
    num_0 = 0
    tours = Tour.all
    tours = tours.where("lower(itinerary) like ?", "%#{itinerary.downcase}%") if itinerary.present?
    tours = tours.where("lower(name) like ?", "%#{name.downcase}%") if name.present?
    # tours = tours.where("lower(name) like ?", "%#{name.downcase}%") if name.present?
    #
    tours = tours.where("price >= ?", min_price) if min_price.present?
    tours = tours.where("price <= ?", max_price) if max_price.present?

    tours = tours.where("seats > ?",num_0) if seats == num_1

    tours = tours.where("start_date >=?", start_date_from) if start_date_from.present?
    tours = tours.where("start_date <=?", start_date_to) if start_date_to.present?
  end
end

app/models/tour.rb
class Tour < ApplicationRecord
  belongs_to :agent
  has_many :bookmarks, dependent: :destroy
  has_many :bookings, dependent: :destroy

  validates :name, :presence => true
  validates :description, :presence => true
  validates :price, :presence => true,:numericality => {:greater_than => 0}
  validates :booking_deadline, :presence => true
  validates :start_date, :presence => true
  validates :end_date, :presence => true
  validates :start_location, :presence => true
  validates :itinerary, :presence => true
  validates :seats, :presence => true , :numericality => {:greater_than_or_equal_to => 0}
  # validates :agent_id, :presence => true
  validates :status, :presence => true
  validates :country, :presence => true
  validates :state, :presence => true
  #adding the class of uploader to the model where it needs to be uploaded/shown
  mount_uploader :image, ImageUploader

end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/agents_helper.rb
module AgentsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user, role)
    session[:user_id] = user.id
    session[:role] = role
  end

  def current_user
    if session[:user_id]
      if session[:role]=='Customer'
        @current_user ||= Customer.find_by(id: session[:user_id])
      else if session[:role]=='Agent'
        @current_user ||= Agent.find_by(id: session[:user_id])
      else
        @current_user ||= Admin.find_by(id: session[:user_id])
      end
      end
    end
  end

  def logged_in?
    !current_user.nil?
    # cookies[:role]
  end

  def log_out
    session.delete :user_id
    session.delete :role
    @current_user = nil
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/tours_helper.rb
module ToursHelper
end

app/views/admins/_form.html.erb
<%= form_with(model: admin, local: true) do |form| %>
  <% if admin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(admin.errors.count, "error") %> prohibited this admin from being saved:</h2>

      <ul>
      <% admin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.text_field :password %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admins/edit.html.erb
<h1>Editing Admin</h1>

<%= render 'form', admin: @admin %>

<%= link_to 'Show', @admin %> |
<%= link_to 'Back', admins_path %>

app/views/admins/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Admins</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @admins.each do |admin| %>
      <tr>
        <td><%= admin.email %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Admin', new_admin_path %>

app/views/admins/new.html.erb
<h1>New Admin</h1>

<%= render 'form', admin: @admin %>

<%= link_to 'Back', admins_path %>

app/views/admins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @admin.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @admin.email %>
</p>

<%= link_to 'Edit Profile', edit_admin_path(@admin) %> |
<%= link_to 'View all Customers', customers_path %> |
<%= link_to 'View all Agents', agents_path %> |
<%= link_to 'View all Tours', tours_path %> |
<%= link_to 'New Agent', new_agent_path %> |
<%= link_to 'New Customer', new_customer_path %> |
<%#= link_to 'Back', admins_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TourManagementSystem</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header>
    <div >
      <div style="margin-left:85%">
        <% if logged_in? %>
          <%= link_to "Home Page",    @current_user %>
          <%= button_to 'Log out'.html_safe, '/logout', method: :delete %>
        <% else %>
          <%= link_to "Home",  '/home' %>
          <%= link_to "Log in", '/login' %>
        <% end %>
      </div>
    </div>
  </header>
    <%= yield %>
  </body>
</html>