config/routes.rb
Rails.application.routes.draw do
  resources :reviews
  resources :bookings
  resources :searches
  resources :bookmarks
  resources :tours
  resources :customers
  resources :agents
  resources :admins

  root 'static_page#home'

  get 'bookmarks/potential_buyers/:tour_id', to: 'bookmarks#potential_buyers'
  get 'bookmarks/add/:customer_id/:tour_id', to: 'bookmarks#add'
  get '/bookings/new/:tour_id', to: 'bookings#new'
  get '/bookings/:booking_id/:tour_id', to: 'bookings#destroy'
  get '/reviews/:customer_id/:tour_id', to: 'reviews#new'

  # get '/partial_delete/:booking_id', to: 'bookings#partial_delete'
  # get '/partial_delete/bookings/:booking_id/:seats_booked', to: 'bookings#partial_delete'

  get '/home', to: 'static_page#home'
  get    '/signup',  to: 'sessions#redirect'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'




  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :customer
  belongs_to :tour

  validates :seats_booked, :numericality => { greater_than: 0}
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:show, :edit , :update]

  # GET /bookings
  # GET /bookings.json
  def index
    @bookings = Booking.all
  end

  # GET /bookings/1
  # GET /bookings/1.json
  def show
  end

  # GET /bookings/new
  def new
    @booking = Booking.new
  end

  # GET /bookings/1/edit
  def edit
  end

  # POST /bookings
  # POST /bookings.json
  def create
    @booking = Booking.new(booking_params)
    @tour = Tour.find(booking_params[:tour_id])
    @booking_waitlisted = Booking.new(booking_params)
    if (@tour.seats.to_i >= booking_params[:seats_booked].to_i)
      seats = @tour.seats.to_i - booking_params[:seats_booked].to_i
      @tour.seats = seats
      @tour.save
      @booking.status = 1
    else
      if (booking_params[:preference] == "Book available seats" && @tour.seats.to_i > 0)
        @booking.seats_booked = @tour.seats
        seats = 0
        @tour.seats = seats
        @tour.save
        @booking.status = 1
      elsif (booking_params[:preference] == "Book Available seats and add remaining to waitlist")
        @booking.seats_booked = @tour.seats
        @tour.seats = 0
        @tour.save
        @booking.status = 1

      #   to handle waitlist seats
        @booking_waitlisted.seats_booked = @booking_waitlisted.seats_booked - @booking.seats_booked
        @booking_waitlisted.status = 0
        @booking_waitlisted.save
      elsif (booking_params[:preference] == "Book only if all seats are available")
        @booking.status = 0
      end
    end
    respond_to do |format|
        if  @booking.save
          format.html { redirect_to bookings_url, notice: 'Booking was successfully created.' }
          format.json { render :show, status: :created, location: @booking }
        else
          format.html { render :new }
          format.json { render json: @booking.errors, status: :unprocessable_entity }
        end
    end
  end

  # PATCH/PUT /bookings/1
  # PATCH/PUT /bookings/1.json
  def update

    # if booking_params[:seats_booked].to_i < @booking.seats_booked.to_i
      tp = params.fetch(:booking).permit(:customer_id,:tour_id,:seats_booked,:preference)
      seats = @booking.seats_booked.to_i - booking_params[:seats_booked].to_i
      @tour = Tour.find(@booking.tour_id)
      @tour.seats = @tour.seats + booking_params[:seats_booked].to_i
      @tour.save
     tp[:seats_booked] = seats

      @tour = Tour.find(@booking.tour_id)

      # booking_db = Booking.order("created_at ASC").find(params[:tour_id])
      booking_db = Booking.all.sort_by {|booking| booking.created_at }
      booking_db.each do |booking|
        if booking.seats_booked <= @tour.seats && booking.status == 0
          @tour.seats = @tour.seats - booking.seats_booked
          booking.status = 1
          booking.save
          @tour.save
          WaitListConfirmationMailer.notify_user(booking.customer).deliver_now
        end
      end


      # format.html { redirect_to @booking, notice: 'cannot delete more seats than booked' }
      # format.json { render :edit, status: :ok, location: @booking }
    # end


    respond_to do |format|
      if @booking.update(tp)
        format.html { redirect_to @booking, notice: 'Booking was successfully updated.' }
        format.json { render :show, status: :ok, location: @booking }
      else
        format.html { render :edit }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end


  # def partial_delete
  #   # @booking = Booking.all
  #   @booking = Booking.find(params[:booking_id])
  #
  #   if (@booking.seats_booked  )
  #
  #   end
  # end



  # DELETE /bookings/1
  # DELETE /bookings/1.json
  def destroy
    @booking = Booking.find(params[:booking_id])
    if @booking.status == 1
      @tour = Tour.find(params[:tour_id])
      puts params
      seats = @tour.seats.to_i + @booking.seats_booked.to_i
      @tour.seats = seats
      @tour.save

      @tour = Tour.find(params[:tour_id])

        # booking_db = Booking.order("created_at ASC").find(params[:tour_id])
      booking_db = Booking.all.sort_by {|booking| booking.created_at }
      booking_db.each do |booking|
          if booking.seats_booked <= @tour.seats && booking.status == 0
            @tour.seats = @tour.seats - booking.seats_booked
            booking.status = 1
            booking.save
            @tour.save
            WaitListConfirmationMailer.notify_user(booking.customer).deliver_now
          end
        end

    end

    @booking.destroy
    respond_to do |format|
      format.html { redirect_to bookings_url, notice: 'Booking was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_booking
      @booking = Booking.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def booking_params
      params.fetch(:booking).permit(:customer_id,:tour_id,:seats_booked,:preference)
    end
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/views/bookings/_form.html.erb
<%= form_with(model: booking, local: true) do |form| %>
  <% if booking.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(booking.errors.count, "error") %> prohibited this booking from being saved:</h2>

      <ul>
      <% booking.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%#= form.label :Customer_ID%>
    <%= form.hidden_field :customer_id, :value => current_user.id %>
  </div>

  <div class="field">
    <%= form.hidden_field :tour_id, :value => params[:tour_id] %>
  </div>

  <div class="field">
    <%= form.label :seats %>
    <%= form.number_field :seats_booked %>
  </div>

  <div>
    <p>1. Book available seats (Only available seats will be booked and remaining seats would be dropped)</p>
    <p>2. Book Available seats and add remaining to waitlist (Available seats will be booked and remaining seats would be added to waitlist)</p>
    <p>3. Book only if all seats are available (If specified seats are not available all the seats would be added to waitlist)</p>
  </div>
  <div class="field">
    <%= form.label :preference %>
    <% if Tour.where(id: params[:tour_id]).pluck(:seats).first > 0%>
    <%= form.select :preference, ['Book available seats', 'Book Available seats and add remaining to waitlist', 'Book only if all seats are available'], { include_blank: true }%>
    <%else%>
      <%= form.select :preference, ['Book Available seats and add remaining to waitlist', 'Book only if all seats are available'], { include_blank: true }%>
    <%end%>
  </div>

  <div class="field">
    <%= form.label :waitlist_count %>
    <%= Booking.where(tour_id: params[:tour_id], status: 0).count %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/bookings/edit.html.erb
<h1>Editing Booking</h1>
<%= form_with(model: @booking, local: true) do |form| %>
<%#= render 'form', booking: @booking %>

<div class="field">
  <%= form.label :seats %>
  <%= form.number_field :seats_booked %>
</div>

  <div class="actions">
    <%= form.submit %>
  </div>

  <%= link_to 'Back', bookings_path %>
<% end %>
<!--<%#= link_to 'Show', @booking %> |-->

app/views/bookings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bookings</h1>

<table>
  <thead>
    <tr>
      <th>Customer Name </th>
      <th>Seats Booked </th>
      <th>Tour Name </th>
      <th>Contact Agent </th>
      <th>Booking Status </th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bookings.each do |booking| %>

    <% if ((booking.customer_id == session[:user_id]) && session[:role] == 'Customer' )|| ((booking.tour.agent.id == session[:user_id]) && session[:role] == 'Agent') || session[:role] == 'Admin' %>
      <tr>
        <td><%= booking.customer.name %> </td>
        <td><%= booking.seats_booked %> </td>
        <td><%= booking.tour.name %> </td>
        <td><%= booking.tour.agent.name %> </td>
        <% if booking.status == 1  %>
          <td><%= 'Confirmed' %> </td>
        <% else %>
          <td><%= 'Wait Listed' %> </td>
        <%end %>
<!--        <td><%#= link_to 'Delete Booking', "/partial_delete/#{booking.id}" %></td>-->
        <td><%= link_to 'Cancel entire Booking', "/bookings/#{booking.id}/#{booking.tour_id}" %></td>
        <td><%= link_to 'Cancel seats', edit_booking_path(booking) %></td>

        <% if booking.tour.status == 'Completed' && session[:role] == 'Customer' %>
          <td><%= link_to 'Write Review', "reviews/#{booking.customer.id}/#{booking.tour.id}" %></td>
        <% end %>
      </tr>
    <% end %>
    <% end %>
  </tbody>
</table>

<br>
<%#= link_to 'Back', show_customer_path %>
<%#= link_to 'New Booking', new_booking_path %>
<a href="javascript:history.back()" class="btn btn-default">Back</a>

app/views/bookings/new.html.erb
<h1>New Booking</h1>

<%= render 'form', booking: @booking %>
<%#= tour.id %>
<%= link_to 'Back', tours_path %>

app/views/bookings/partial_delete.html.erb
<% if logged_in? %>
  <p id="notice"><%= notice %></p>

  <h1>Delete Booking</h1>

  <%= form_with(model: @booking, local: true) do |form| %>

    <%= @booking.seats_booked %>
    <div class="field">
      <%= form.label :seats_booked%>
      <%= form.text_field :seats_booked %>
    </div>

    <div class="field">
      <%= form.hidden_field :tour_id, :value => @booking.tour.id %>
      <%= form.hidden_field :customer_id, :value => @booking.customer.id %>
      <%= form.hidden_field :preference, :value => @booking.preference %>
      <%#= form.hidden_field :tour_id, :value =>  %>
    </div>

    <div class="actions">
      <%#= form.submit 'Submit'%>
      <%= link_to 'Modify Booking', "bookings/#{@booking.id}/#{form.seat_booked}" %>
    </div>
  <% end %>

  <a href="javascript:history.back()" class="btn btn-default">Back</a>
  <%# end %>
<% else %>
    <script type="text/javascript">
        window.location.href="/login"  //Redirect to login for unlogged in users
    </script>
<% end %>

app/views/bookings/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_booking_path(@booking) %> |
<%= link_to 'Back', bookings_path %>