config/routes.rb
Rails.application.routes.draw do
  resources :reviews
  resources :bookings
  resources :searches
  resources :bookmarks
  resources :tours
  resources :customers
  resources :agents
  resources :admins

  root 'static_page#home'

  get 'bookmarks/potential_buyers/:tour_id', to: 'bookmarks#potential_buyers'
  get 'bookmarks/add/:customer_id/:tour_id', to: 'bookmarks#add'
  get '/bookings/new/:tour_id', to: 'bookings#new'
  get '/bookings/:booking_id/:tour_id', to: 'bookings#destroy'
  get '/reviews/:customer_id/:tour_id', to: 'reviews#new'

  # get '/partial_delete/:booking_id', to: 'bookings#partial_delete'
  # get '/partial_delete/bookings/:booking_id/:seats_booked', to: 'bookings#partial_delete'

  get '/home', to: 'static_page#home'
  get    '/signup',  to: 'sessions#redirect'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'




  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :bookings, dependent: :destroy

  EMAIL_FORMAT = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: { case_sensitive: false,   message: "This account already exists. Go to Login"  }, format: { with: EMAIL_FORMAT }
  validates :name, presence: true
  validates :password, presence: true, confirmation: true

  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.all
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to '/login', notice: 'Customer was successfully created. Please login to continue!!' }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      if (session[:role] == 'Admin')
        format.html { redirect_to @customer, notice: 'Customer was successfully destroyed.' }
        format.json { head :no_content }
      else
        format.html { redirect_to '/home', notice: 'Customer was successfully destroyed.' }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      params.require(:customer).permit(:email, :password, :name)
    end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_form.html.erb
<%= form_with(model: customer, local: true) do |form| %>
  <% if customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
      <% customer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :customer_name,  placeholder: "Enter Name"  %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.email_field :email, id: :customer_email, class: 'form-control', placeholder: "Enter Email"  %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password, id: :customer_password, placeholder: "Enter Password"%><br>
    <%= form.label :password_confirmation, "Confirm Password" %>
    <%= form.password_field :password_confirmation, id: :customer_password, placeholder: "Enter password again"%>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/customers/edit.html.erb
<h1>Editing Customer</h1>

<%= render 'form', customer: @customer %>

<%#= link_to 'Back', customers_path %>
<a href="javascript:history.back()" class="btn btn-default">Back</a>

app/views/customers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Customers</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.email %></td>
        <td><%= customer.name %></td>
<!--        <td><%#= link_to 'Show', customer %></td>-->
        <td><%= link_to 'Edit', edit_customer_path(customer) %></td>
        <td><%= button_to 'Destroy', customer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Customer', new_customer_path %>

app/views/customers/new.html.erb
<h1>New Customer</h1>

<%= render 'form', customer: @customer %>

<%= link_to 'Back', customers_path %>

app/views/customers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @customer.email %>
</p>

<p>
  <strong>Name:</strong>
  <%= @customer.name %>
</p>

<%= link_to 'Edit Profile', edit_customer_path(@customer) %> |
<%= link_to 'View Tours', tours_path%> |
<%= link_to 'View Bookings', bookings_path%> |
<%= link_to 'View Bookmarks', bookmarks_path %> |
<%= button_to 'Destroy', @customer, method: :delete, data: { confirm: 'Are you sure?' } %> |
<%= link_to 'View Reviews', reviews_path %><br><br>