config/routes.rb
Rails.application.routes.draw do
  resources :reviews
  resources :bookings
  resources :searches
  resources :bookmarks
  resources :tours
  resources :customers
  resources :agents
  resources :admins

  root 'static_page#home'

  get 'bookmarks/potential_buyers/:tour_id', to: 'bookmarks#potential_buyers'
  get 'bookmarks/add/:customer_id/:tour_id', to: 'bookmarks#add'
  get '/bookings/new/:tour_id', to: 'bookings#new'
  get '/bookings/:booking_id/:tour_id', to: 'bookings#destroy'
  get '/reviews/:customer_id/:tour_id', to: 'reviews#new'

  # get '/partial_delete/:booking_id', to: 'bookings#partial_delete'
  # get '/partial_delete/bookings/:booking_id/:seats_booked', to: 'bookings#partial_delete'

  get '/home', to: 'static_page#home'
  get    '/signup',  to: 'sessions#redirect'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'




  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/tour.rb
class Tour < ApplicationRecord
  belongs_to :agent
  has_many :bookmarks, dependent: :destroy
  has_many :bookings, dependent: :destroy

  validates :name, :presence => true
  validates :description, :presence => true
  validates :price, :presence => true,:numericality => {:greater_than => 0}
  validates :booking_deadline, :presence => true
  validates :start_date, :presence => true
  validates :end_date, :presence => true
  validates :start_location, :presence => true
  validates :itinerary, :presence => true
  validates :seats, :presence => true , :numericality => {:greater_than_or_equal_to => 0}
  # validates :agent_id, :presence => true
  validates :status, :presence => true
  validates :country, :presence => true
  validates :state, :presence => true
  #adding the class of uploader to the model where it needs to be uploaded/shown
  mount_uploader :image, ImageUploader

end

app/controllers/tours_controller.rb
class ToursController < ApplicationController
  before_action :set_tour, only: [:show, :edit, :update, :destroy]

  # GET /tours
  # GET /tours.json
  def index
    @tours = Tour.all
  end

  # GET /tours/1
  # GET /tours/1.json
  def show
  end

  # GET /tours/new
  def new
    @tour = Tour.new
  end

  # GET /tours/1/edit
  def edit
  end

  # POST /tours
  # POST /tours.json
  def create
    @tour = Tour.includes(:agent).new(tour_params)
    respond_to do |format|
      if @tour.save
        format.html { redirect_to @tour, notice: 'Tour was successfully created.'}
        format.json { render :show, status: :created, location: @tour }
      else
        format.html { render :new }
        format.json { render json: @tour.errors, status: :unprocessable_entity }
      end
    end
  end

  def decrement_seats
    @tour = Tour.all
  end

  # PATCH/PUT /tours/1
  # PATCH/PUT /tours/1.json
  def update
    respond_to do |format|
      if @tour.update(tour_params)
        format.html { redirect_to @tour, notice: 'Tour was successfully updated.' }
        format.json { render :show, status: :ok, location: @tour }
      else
        format.html { render :edit }
        format.json { render json: @tour.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tours/1
  # DELETE /tours/1.json
  def destroy
    @tour.destroy
    respond_to do |format|
      format.html { redirect_to tours_url, notice: 'Tour was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tour
      @tour = Tour.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tour_params
      params.require(:tour).permit(:id, :name, :description, :image, :price, :booking_deadline, :start_date, :end_date, :start_location, :itinerary,:country, :state, :agent_id, :seats, :status,:remove_image)
    end
end

app/helpers/tours_helper.rb
module ToursHelper
end

app/views/tours/_form.html.erb
<%= form_with(model: tour, local: true) do |form| %>
  <% if tour.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tour.errors.count, "error") %> prohibited this tour from being saved:</h2>

      <ul>
      <% tour.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, placeholder: "Enter Name"   %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description%>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>

  <div class="field">
    <%= form.label :booking_deadline %>
    <%= form.date_select :booking_deadline %>
  </div>

  <div class="field">
    <%= form.label :start_date %>
    <%= form.date_select :start_date %>
  </div>

  <div class="field">
    <%= form.label :end_date %>
    <%= form.date_select :end_date %>
  </div>

  <div class="field">
    <%= form.label :start_location %>
    <%= form.text_field :start_location %>
  </div>

  <div class="field">
    <%= form.label :itinerary %>
    <%= form.text_area :itinerary %>
  </div>

  <div class="field">
    <%= form.label :countries %>
    <%= form.text_area :country %>
  </div>

  <div class="field">
    <%= form.label :states %>
    <%= form.text_area :state %>
  </div>

  <div class="field">
    <%= form.label :seats %>
    <%= form.number_field :seats %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.select :status, ['In Future', 'Completed', 'Cancelled']%>
  </div>

  <% if session[:role] == 'Admin' %>
    <div class="field">
      <%= form.label "Agent" %>
      <%= select("tour", "agent_id", Agent.all.collect{ |c| [ c.name, c.id ]}, { include_blank: true }) %>
  <% else %>
    <%= form.label "Agent" %>
    <%= form.select :agent_id, [[current_user.name,current_user.id]] %>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label "Upload Tour Images"%>
    <%= form.file_field :image %>
    <% if form.object.image? %>
      <%#= image_tag form.object.image.url %>
      <%= form.label :remove_image %>
      <%= form.check_box :remove_image %>
    <% end %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tours/edit.html.erb
<h1>Editing Tour</h1>

<%= render 'form', tour: @tour %>

<%= link_to 'Back', tours_path %>

app/views/tours/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tours</h1>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th>
      <th>Booking deadline</th>
      <th>Start date</th>
      <th>End date</th>
      <th>Start location</th>
      <th>Itinerary</th>
      <th>Contact agent</th>
      <th>Seats</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tours.each do |tour| %>
      <tr>
        <td><%= tour.id %></td>
        <td><%= tour.name %></td>
        <td><%= tour.description %></td>
        <td><%= tour.price %></td>
        <td><%= tour.booking_deadline %></td>
        <td><%= tour.start_date %></td>
        <td><%= tour.end_date %></td>
        <td><%= tour.start_location %></td>
        <td><%= tour.itinerary %></td>
        <td><%= tour.agent.name%></td>
        <td><%= tour.seats %></td>
        <td><%= tour.status %></td>
<!--        <td><%#= session[:user_id] %></td>-->
        <td><%= link_to 'Show', tour %></td>
        <% unless session[:role] == 'Customer'%>  <!-- Only Logged in Realtor and Admin has access -->
          <td> <%= link_to_if(session[:user_id] == tour.agent_id,  'Bookmarked Customer', "/bookmarks/potential_buyers/#{tour.id}"  ) %></td>
          <%end %>
        <% unless session[:role] == 'Customer'%>  <!-- Only Logged in Realtor and Admin has access -->
          <td> <%= link_to_if(session[:user_id] == tour.agent_id,  'Booked Customer', bookings_path  ) %></td>
        <%end %>
        <%if session[:role] != 'Customer' %>
          <td><%= link_to_if(tour.status != 'Completed' && (tour.agent_id == session[:user_id] && session[:role] == 'Agent') || session[:role] == 'Admin','Edit', edit_tour_path(tour))%></td>
          <% if (tour.status != 'Completed' &&(tour.agent_id == session[:user_id] && session[:role] == 'Agent') || session[:role] == 'Admin') %>
              <td><%= button_to 'Destroy', tour, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
          <% if(tour.status == 'Completed' && (session[:role] == 'Admin' || current_user.id == tour.agent.id)) %>
            <td><%=link_to 'View Reviews', reviews_path %></td>
          <% end %>
        <% end %>
        <% if (session[:role] == 'Customer' || session[:role] == 'Admin') && tour.status == "In Future" %>
          <td><%= link_to 'Bookmark', "/bookmarks/add/#{session[:user_id]}/#{tour.id}"%></td>
          <td><%= link_to 'Book', "/bookings/new/#{tour.id}" %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<!--only for agent and admin-->
<% if (session[:role] == 'Admin' || session[:role] == 'Customer')   %>
  <%= link_to 'Search Tours', new_search_path %>
  <% if(session[:role] == 'Admin' || session[:role] == 'Agent') %>
    <%= link_to 'New Tour', new_tour_path  %>
    <%end %>
<% end %>

<a href="javascript:history.back()" class="btn btn-default">Back</a>

app/views/tours/new.html.erb
<h1>New Tour</h1>

<%= render 'form', tour: @tour %>

<a href="javascript:history.back()" class="btn btn-default">Back</a>

app/views/tours/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id:</strong>
  <%= @tour.id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @tour.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @tour.description %>
</p>

<p>
  <strong>Photo:</strong>
  <%= image_tag @tour.image_url.to_s %>
</p>

<p>
  <strong>Price:</strong>
  <%= @tour.price %>
</p>

<p>
  <strong>Booking deadline:</strong>
  <%= @tour.booking_deadline %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @tour.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @tour.end_date %>
</p>

<p>
  <strong>Start location:</strong>
  <%= @tour.start_location %>
</p>

<p>
  <strong>Itinerary:</strong>
  <%= @tour.itinerary %>
</p>

<p>
  <strong>Country:</strong>
  <%= @tour.country %>
</p>

<p>
  <strong>State:</strong>
  <%= @tour.state %>
</p>

<p>
  <strong>Contact agent:</strong>
  <%= @tour.agent_id %>
</p>

<p>
  <strong>Seats:</strong>
  <%= @tour.seats %>
</p>

<p>
  <strong>Status:</strong>
  <%= @tour.status %>
</p>


<!--Check for agent and admin edit only-->
<%# if session[:role] == 'Agent' || session[:role] == 'Admin'%>
<!--  <%#= link_to 'Edit', edit_tour_path(@tour) %> |-->
<%#end %>
<%= link_to 'Back', tours_path %>